# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
## Steps:
## 1. Prepare environment grid:
### 1.1. OS: Ubuntu, Windows, MacOS
### 1.2. Python version: 3.8, 3.9, 3.10
## 2. Install dependencies
### 2.1. Install pip, wheel, setuptools, tox
### 2.2. Install ROICaT dependencies from requirements_GPU.txt
## 3. Run tests using tox

name: ROICaT-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# permissions:
#   contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    # Do not ignore bash profile files. From:
    # https://github.com/marketplace/actions/setup-miniconda
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: PowerShell Core
      shell: pwsh
      run: |
          conda info
          conda list
    
    - name: Check out repository code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.15"
    
    - name: cd to $GITHUB_WORKSPACE
      run: |
          echo "begin PATH: $PATH;"
          echo "begin pwd: $(pwd);"
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          cd $GITHUB_WORKSPACE
          echo "after cd PATH: $PATH;"
          echo "after cd pwd: $(pwd);"
          echo "after cd ls -l:"
          ls -l
        
    # - uses: conda-incubator/setup-miniconda@v2
    #   with:
    #   #     channels: conda-forge, defaults
    #       miniconda-version: "latest"
    #       environment-file: environment_GPU.yml
    #       activate-environment: ROICaT
    #   #     auto-update-conda: true
    #   #     auto-activate-base: true

    - name: Make conda environment
      run: |
          echo "pwd: $(pwd);"
          echo "ls -l:"
          ls -l
          conda env create --file environment_GPU.yml
          conda activate ROICaT || true

    - name: Install roicat
      run: |
          pip install -e .
          
    - name: Test with tox
      run: |
        tox
      env:
        PLATFORM: ${{ matrix.os }}
        PYTHON_VERSION: ${{ matrix.python-version }}