# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ROICaT-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        activate-environment: ROICaT
        auto-activate-base: true
        auto-update-conda: false
        remove-profiles: true
        architecture: x64
        clean-patched-environment-file: true
        run-post: true

    - name: PowerShell Core
      shell: pwsh
      run: |
          conda info
          conda list
    
    - name: Check out repository code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.15"
    
    - name: Install dependencies
      run: |
        ## make sure we are using the right directory
        ls -l
        cd $GITHUB_WORKSPACE
        ls -l
        ## check current directory (pwd)
        pwd
        conda info
        
        conda activate ROICaT || true
        python -m pip install --upgrade pip setuptools wheel pytest tox
        # python -m pip install -r requirements_GPU.txt
        # if [ -f requirements_GPU.txt ]; then pip install -r requirements_GPU.txt; fi
        # conda env update --name ROICaT --file environment_GPU.yml
    - name: Install ROICaT with pip dependencies
      run: |
        pip install -e .
    - name: Install ROICaT test dependencies
      run: |
        pip install pytest
    - name: Test with pytest
      run: |
        pytest -v